---
title: "Viz part 1"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

# knitr::opts_chunk$set(fig.width = 6, fig.asp = 0.6, fig.height = 0.3)
```

Get the data for plotting today.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Make plots!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

Pipes and stuff

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point()

ggp_nyc_weather <- 
  weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point()

ggp_nyc_weather
```

## Fancy plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color=name)) +
  geom_point() + 
  geom_smooth() # creates a smooth curves for each variable

ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color=name)) + 
  geom_smooth() # creates a smooth curve for all data

# never plot curve without data points (geom_smooth without geom_point)

ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color=name)) + 
  geom_smooth(se = FALSE) # hides standard error bracket

ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color=name), alpha = 0.3) +  # makes it 30% opaque
  geom_smooth(se = FALSE) 
```

Plot with facets: previous plot is still difficult to see, now split into facets for each location

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color=name)) +
  geom_point(alpha=0.3) + 
  geom_smooth() +
  facet_grid(. ~ name)

ggplot(weather_df, aes(x = tmin, y = tmax, color=name)) +
  geom_point(alpha=0.3) + 
  geom_smooth() +
  facet_grid(name ~ .)
```

Let's try a different plot - temps are boring

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth()

ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth()

ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) + # add precipitation points (size)
  geom_smooth()

ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth() +
  facet_grid(. ~ name)
```

Assign specific colors

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x=date, y=tmax)) +
  geom_point(color = "blue") # careful not to put this in aes()

weather_df |> 
  filter(name != "CentralPark_NY") |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point()

weather_df |> 
  filter(name != "CentralPark_NY") |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.7, size = 0.5)
```

```{r}
weather_df |>  
  ggplot(aes(x = date, y = tmax)) +
  geom_hex()
```
## Univariate plotting

Histogram

```{r}
ggplot(weather_df, aes(x = tmax)) +
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + # we observe stacking
  geom_histogram()

# one way to deal with stacking
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge")

# Let's use a density plot
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density()

ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3) # to see clearer

ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3, adjust = 2) # adjust to change how smooth curves are
```

Using boxplots

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_boxplot()
```

Violin plots

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_violin()
```

Ridge plot

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```

Line plot

```{r}
weather_df |> 
  filter(name == "Molokai_HI") |> 
  ggplot(aes(x = date, y = tmax)) +
  geom_line() 

weather_df |> 
  filter(name == "Molokai_HI") |> 
  ggplot(aes(x = date, y = tmax)) +
  geom_line(alpha = 0.5) + 
  geom_point(size = 0.5)
```

## Saving plots

```{r}
ggp_weather <-
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_weather

ggsave("results/ggp_weather.pdf", ggp_weather)
```

## Embedding plots

```{r, fig.width = 12, fig.height = 12}
ggp_weather

# other options: fig.asp
```







